### ISSUE TITLE
May I ask how to use Openfeign in Spring Cloud 2023 version

### ISSUE THREAD

**Issue by ysr1127** [KouShenhai/KCloud-Platform-IoT#1046]
May I ask how to use Openfeign in Spring Cloud 2023 version

**Comment by KouShenhai** [comment]
你遇到什么问题？

**Comment by ysr1127** [comment]
我在尝试升级版本时遇到了openfeign无法注入bean的问题，在springboot3.1.6和springcloud2022.0.4时代码没有问题，升级到3.2.0和2023.0.0后无法注入openfeign bean对象

**Comment by KouShenhai** [comment]
小问题

**Comment by ysr1127** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scopedTarget.combatController' defined in file [E:\projects\platform\microservice-search\target\classes\com\zstech\microservicesearch\controller\CombatController.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'com.zstech.microservicesearch.feign.BasicDataFeignService': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:802)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:241)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:364)
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:375)
	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:179)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:361)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1173)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.eagerlyInitialize(RefreshScope.java:126)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:118)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.onApplicationEvent(RefreshScope.java:113)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.onApplicationEvent(RefreshScope.java:68)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:968)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)
	at com.zstech.microservicesearch.MicroserviceSearchApplication.main(MicroserviceSearchApplication.java:27)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.zstech.microservicesearch.feign.BasicDataFeignService': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:188)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:124)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1810)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1277)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1651)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1395)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1348)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:911)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 29 common frames omitted
Caused by: java.lang.IllegalStateException: Method BasicDataFeignService#getVirtualPlateListForMore(VirtualPlateListInputDTO) not annotated with HTTP method type (ex. GET, POST)
不是http方法类型的问题

**Comment by ysr1127** [comment]
大佬，请问怎么解决这个问题

**Comment by KouShenhai** [comment]
spring cloud 2022 使用是mvc

更新至 spring cloud 2023默认使用的是feign-core 里面的feign注解

```
@Param
@Headers
@RequestLine
```

因此

```
@RequestParam 改为 @Param
@GetMapping/PostMapping/@PutMapping/@DeleteMapping 改为 @RequestLine
```

以下是具体的例子
```
@FeignClient(contextId = "xxx", name = xxx, path = "v1/xxx",
		fallbackFactory = xxxFactory.class)
public interface xxxFeignClient {

	@RequestLine("POST /list")
	@Headers("Content-Type: application/json")
	Result<Datas<xxxCO>> list(@RequestBody XXXQry qry);
}
```

增加feign配置
```
	/**
	 * 如果开启MVC 请查看 {@link FeignClientsConfiguration}
	 * 开启支持@RequestLine @Header @RequestPart
	 */
	@Bean
	public Contract feignContract() {
		return new feign.Contract.Default();
	}
```

[详情查看代码](https://github.com/KouShenhai/KCloud-Platform-Alibaba/tree/master/laokou-common/laokou-common-openfeign)

最后帮我点一个star，也算是对作者的支持

**Comment by ysr1127** [comment]
感谢，已点

**Comment by KouShenhai** [comment]
感谢支持

**Comment by KouShenhai** [comment]
更新第二种，解决方案

我分析了一下，原来是sentinelfeign有问题，默认使用的是feign-core导致出现问题，但自己的代码是使用的springmvc风格，肯定有问题啊

查看 ```SentinelFeign``` 源码 
![image](https://github.com/KouShenhai/KCloud-Platform-Alibaba/assets/48756217/7be6db4f-3114-4057-a4b0-fed18337ec08)

![image](https://github.com/KouShenhai/KCloud-Platform-Alibaba/assets/48756217/0e41514d-779c-4c42-9bf5-a747e294a3fe)
